### ISSUE TITLE
Make user install cicpoffs

### ISSUE THREAD

**Issue by Revival8697** [m5kro/Painless-Porter-CLI#3]
The current way of using cicpoffs is, eh, not ideal. Instead of using `nwjs/libs/cicpoffs` we should ask users to install cicpoffs on their system and use `/usr/bin/cicpoffs` in the scripts.

See https://github.com/Revival8697/RPG-Maker-MV-MZ-Linux-Guide/blob/7e8248a5141015be69a46d05877277f157c20091/Game.sh

**Comment by m5kro** [comment]
Going with ~/.local/bin/cicpoffs instead so root permissions aren't needed. Also sticking with the auto install so user has to do as little as possible.

**Comment by m5kro** [comment]
Going with ~/.local/bin/cicpoffs instead so root permissions aren't needed. Also sticking with the auto install so user has to do as little as possible.

**Comment by Revival8697** [comment]
> Going with ~/.local/bin/cicpoffs instead so root permissions aren't needed. Also sticking with the auto install so user has to do as little as possible.

You only need root access to install the package.

As it currently is, the mount would fail if you don't have dependencies for `cicpoffs`, installing it to root will allow you to remove `fusemount` check.

**Comment by m5kro** [comment]
Opting to use pacapt to autoinstall fuse. Still using standalone executable so distro detection is not needed.
