### ISSUE TITLE
Respect game's package.json

### ISSUE THREAD

**Issue by Revival8697** [m5kro/Painless-Porter-CLI#4]
Currently, you are using 1 same [package-template.json](https://github.com/m5kro/Painless-Porter-CLI/blob/main/package-template.json) for all games . Each game have their own custom `package.json` with custom values, we should copy it over the game folder and only edit the `name`.

**Comment by m5kro** [comment]
Now using original package.json for MV games. package-template.json will still be used for MZ games as they don't have it.

**Comment by Revival8697** [comment]
> Now using original package.json for MV games. package-template.json will still be used for MZ games as they don't have it.

They do have it. You just have to update it to point to the files in the `www` folder.

**Comment by m5kro** [comment]
Ah you're right. I thought there needed to be two separate package.json, one in www and one outside www because MV was like that. Turns out the extra package.json in the www folder is actually unneeded for both.

**Comment by m5kro** [comment]
Ok should be fixed now.
