### ISSUE TITLE
Automated MZ re-packaging doesn't account for custom asset

### ISSUE THREAD

**Issue by Revival8697** [m5kro/Painless-Porter-CLI#6]
The current script only copy over standard MZ assests and not custom asset (files or directories).
I recommend testing against [SampleGames_EN.zip](https://s3-ap-northeast-1.amazonaws.com/degica-prod.product-files/46029/SampleGames_EN.zip) (direct download link).
This contain projects files, not games. You have to add `Game.exe` to them so your script can detect them.

**Comment by m5kro** [comment]
I see. I'll probably just copy over everything and have an exclusion list for the nwjs files.
